### ISSUE TITLE
current status layout issues at browser width above 1601px

### ISSUE THREAD

**Issue by andreasn** [martinpitt/performance-graphs#30] opened 2020-09-07 10:14 UTC
At 1601px
![Screen Shot 2020-09-07 at 12 13 42](https://user-images.githubusercontent.com/209895/92376923-a0037b00-f103-11ea-8700-222506f40e71.png)

At 1602px
![Screen Shot 2020-09-07 at 12 13 52](https://user-images.githubusercontent.com/209895/92376954-aabe1000-f103-11ea-8f41-b9a94680921d.png)

**Comment by martinpitt** [comment] 2020-09-07 11:15
Duplicate of #10. It's not strictly a matter of screen width -- in most cases, it works fine for me on a 1920px screen. There's something more subtle going on.

**Closed by martinpitt** 2020-09-07 11:15 UTC
